#
# This workflow calls the main distribution pipeline from DuckDB to build, test and (optionally) release the extension
#
name: Main Extension Distribution Pipeline
on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' || github.sha }}
  cancel-in-progress: true

jobs:
  duckdb-stable-build:
    name: Build extension binaries
    uses: duckdb/extension-ci-tools/.github/workflows/_extension_distribution.yml@${{matrix.version}}
    strategy:
      matrix:
        version:
          - v0.10.2
          - v0.10.3
    with:
      duckdb_version: ${{ matrix.version }}
      extension_name: affine_gap
      exclude_archs: windows_amd64;windows_amd64_rtools;osx_amd64;osx_arm64;wasm_mvp;wasm_eh;wasm_threads

#  duckdb-stable-deploy:
#    name: Deploy extension binaries
#    needs: duckdb-stable-build
#    uses: ./.github/workflows/_extension_deploy.yml
#    secrets: inherit
#    with:
#      duckdb_version: v0.10.2
#      extension_name: affine_gap
#      deploy_latest: ${{ startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/main' }}
